{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-app
  labels: backend-app
spec:
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: backend-app
  targetCPUUtilizationPercentage: {{ .Values.hpa.percentage }}
{{- end -}}