apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-chart
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ./helm_charts/frontend-app
    repoURL: 'https://github.com/Ahmed-Soli/3tier-frontend-backend-db.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
