---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: {{.Values.app.mongodb_data.image}}
        name: mongo
        env:
          # Use secret in real usage
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.app.mongodb_data.env.USER }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.app.mongodb_data.env.PASS }}
        ports:
        - containerPort: {{ .Values.app.mongodb_data.container_port }}
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
