---
apiVersion: v1
kind: Service
metadata: 
  name: "mongo"
  labels: 
    app: "mongo"
spec:
  ports:
    - name: "mongo"
      port: {{ .Values.app.mongodb_data.container_port }}
      nodePort: {{ .Values.app.mongodb_data.node_port }}
  type: "NodePort"
  selector: 
    app: "mongo"