app:
  replicas: 1
  container:
    port: "3000"
    image: ahmedsoliman202/3tier-frontend-app
  service:
    target_port: 3000
    node_port: 30008


hpa:
  enable: false
  minReplicas: 4
  maxReplicas: 10
  percentage: 50