# reference in the docs here 
# https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
---
apiVersion: "v1"
kind: "Service"
metadata: 
  name: "mongo"
  labels: 
    app: "mongo"
spec: 
  ports: 
    - name: "mongo"
      port: 27017
      nodePort: 30332
  type: "NodePort"
  selector: 
    app: "mongo"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "mongo"
spec: 
  selector: 
    matchLabels: 
      app: "mongo"
  replicas: 1
  strategy: 
    type: "RollingUpdate"
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template: 
    metadata: 
      labels: 
        app: "mongo"
    spec: 
      containers: 
        - name: "mongo"
          image: "mongo"
          imagePullPolicy: "Always"
          env: 
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "username"
              
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "password"
          ports: 
            - containerPort: 27017
              name: "mongo"
              
          volumeMounts: 
            - name: "mongo-persistent-storage"
              mountPath: "/data/db"
              
      volumes: 
        - name: "mongo-persistent-storage"
          persistentVolumeClaim: 
            claimName: "mongo-pvc"